# Generated by Django 5.1.7 on 2025-03-09 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='media_files/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.IntegerField(unique=True)),
                ('title_current_city', models.CharField(max_length=50)),
                ('title_home_city', models.CharField(max_length=50)),
                ('main_text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BuzzWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buzzword', models.CharField(max_length=100)),
                ('linked_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_book.mediafile')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buzzwords', to='app_book.text')),
            ],
        ),
    ]
