# Generated by Django 5.1.7 on 2025-03-09 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='title_home_city',
            field=models.CharField(choices=[('rus', 'Санкт-Петербург'), ('eng', 'Saint Petersburg')], max_length=3),
        ),
        migrations.CreateModel(
            name='BuzzWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buzzword', models.CharField(max_length=100)),
                ('linked_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_book.mediafile')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buzzword', to='app_book.text')),
            ],
        ),
        migrations.DeleteModel(
            name='BuzzWords',
        ),
    ]
