# Generated by Django 5.1.7 on 2025-03-09 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0002_alter_text_title_home_city_buzzword_delete_buzzwords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buzzword',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buzzword_names', to='app_book.text'),
        ),
    ]
