# Generated by Django 5.1.7 on 2025-03-12 17:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0004_bookmarks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmarks',
            unique_together={('user', 'bookmark')},
        ),
    ]
