# Generated by Django 5.1.7 on 2025-03-13 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0005_alter_bookmarks_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmarks',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bookmarks',
            name='bookmark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to='app_book.text'),
        ),
    ]
