# version: '3.9'

# services:
#   web:
#     build: .
#     container_name: django_app
#     command: gunicorn project_book.wsgi:application --bind 0.0.0.0:8000
#     volumes:
#       - static_volume:/app/app_for_book/staticfiles
#       - media_volume:/app/app_for_book/app_book/static/images/pictures_for_buzzwords
#       - ./app_for_book/db.sqlite3:/app/app_for_book/db.sqlite3
#     expose:
#       - 8000

#   nginx:
#     image: nginx:latest
#     container_name: nginx
#     ports:
#       - "8000:80"
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#       - static_volume:/app/app_for_book/staticfiles
#       - media_volume:/app/app_for_book/app_book/static/images/pictures_for_buzzwords
#     depends_on:
#       - web

# volumes:
#   static_volume:
#   media_volume:

version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      gunicorn project_book.wsgi:application --bind 0.0.0.0:8000
      "
    env_file:
      - .env
    volumes:
      - static_volume:/app/app_for_book/staticfiles
      - ./app_for_book/db.sqlite3:/app/app_for_book/db.sqlite3
      - ./secrets/bookapp-454110-1e63ec402267.json:/app/secrets/bookapp-454110-1e63ec402267.json:ro
    expose:
      - 8000

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/app_for_book/staticfiles
    depends_on:
      - web

volumes:
  static_volume:
