# Generated by Django 5.1.7 on 2025-03-24 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='media_files/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('chapter_number', models.IntegerField(primary_key=True, serialize=False)),
                ('title_current_city', models.CharField(max_length=50)),
                ('title_current_city_coord', models.CharField(max_length=100)),
                ('title_home_city', models.CharField(choices=[('rus', 'Санкт-Петербург'), ('eng', 'Saint Petersburg')], max_length=3)),
                ('main_text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('favorites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='app_book.mediafile')),
            ],
        ),
        migrations.CreateModel(
            name='BuzzWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buzzword', models.CharField(max_length=100)),
                ('linked_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_book.mediafile')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buzzword_names', to='app_book.text')),
            ],
        ),
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bookmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmark', to='app_book.text')),
            ],
        ),
    ]
