# Generated by Django 5.1.7 on 2025-08-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0002_text_chapter_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='main_text',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='text',
            name='title_current_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
