# Generated by Django 5.1.7 on 2025-08-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_book', '0003_alter_text_main_text_alter_text_title_current_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='title_home_city',
            field=models.CharField(blank=True, choices=[('rus', 'Санкт-Петербург'), ('eng', 'Saint Petersburg')], max_length=3, null=True),
        ),
    ]
